version: "3.8"

services:


  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network

  prometheus:
    build: ./prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: always
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

